export const DATE_FORMAT_DISPLAY_YYYY_MM_DD = "YYYY년 MM월 DD일";

export const DATE_FORMAT_DISPLAY_MM_DD_A_HH_MI = `MM/DD _ A HH:mm`;

export const DATE_FORMAT_DISPLAY_YYYY_MM_DD_A_HH_MI = `${DATE_FORMAT_DISPLAY_YYYY_MM_DD} A hh:mm`;
export const DATE_FORMAT_DISPLAY_YYYY_MM_DD_D_A_HH_MI = `${DATE_FORMAT_DISPLAY_YYYY_MM_DD} (dd) A hh:mm`;
