export enum FilterJobType {
  Accounting = 'accounting',
  Ai = 'ai',
  Construction = 'construction',
  Customer = 'customer',
  Design = 'design',
  Driver = 'driver',
  Education = 'education',
  Finance = 'finance',
  Game = 'game',
  Hr = 'hr',
  It = 'it',
  Legal = 'legal',
  Marketing = 'marketing',
  Md = 'md',
  Media = 'media',
  Medical = 'medical',
  Production = 'production',
  Public = 'public',
  Purchase = 'purchase',
  Research = 'research',
  Sales = 'sales',
  Semiconductor = 'semiconductor',
  Service = 'service',
  Strategy = 'strategy'
}
